# Generated by Django 2.1.2 on 2018-12-29 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Insecurity', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='insecuremodel',
            table='InsecureModel',
        ),
    ]
